#pragma once

#define BYPASS_DRIVER_DEVICE 0x8000
#define BYPASS_DRIVER_READ_GAME_MEMORY   CTL_CODE(BYPASS_DRIVER_DEVICE, 0x800, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define BYPASS_DRIVER_WRITE_GAME_MEMORY  CTL_CODE(BYPASS_DRIVER_DEVICE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)